# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Anchorbrowser < Formula
  desc "AnchorBrowser CLI for sessions, tasks, and identities"
  homepage "https://anchorbrowser.io"
  version "0.1.23"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/anchorbrowser/cli/releases/download/v0.1.23/anchorbrowser_0.1.23_darwin_amd64.tar.gz"
      sha256 "777374cf0b21849c73b07449fff18adb73533ae04ec6df27a179c4b6b6895312"

      define_method(:install) do
        bin.install "anchorbrowser"
        system "#{bin}/anchorbrowser", "backend", "install"
        generate_completions_from_executable(bin/"anchorbrowser", "__completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/anchorbrowser/cli/releases/download/v0.1.23/anchorbrowser_0.1.23_darwin_arm64.tar.gz"
      sha256 "1d32f41512b3e0d2e18d61f33ad2f5d3995afcbf2d4a4f9039ca2d8682e466d3"

      define_method(:install) do
        bin.install "anchorbrowser"
        system "#{bin}/anchorbrowser", "backend", "install"
        generate_completions_from_executable(bin/"anchorbrowser", "__completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/anchorbrowser/cli/releases/download/v0.1.23/anchorbrowser_0.1.23_linux_amd64.tar.gz"
      sha256 "2eed4329899696616fe3233e6dc842db2a124de1be0e6d6219e2a8e80f12c695"
      define_method(:install) do
        bin.install "anchorbrowser"
        system "#{bin}/anchorbrowser", "backend", "install"
        generate_completions_from_executable(bin/"anchorbrowser", "__completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/anchorbrowser/cli/releases/download/v0.1.23/anchorbrowser_0.1.23_linux_arm64.tar.gz"
      sha256 "ea15aeb926d6ef5471542241670e568063ab68e7ddd97d0627278190705130f2"
      define_method(:install) do
        bin.install "anchorbrowser"
        system "#{bin}/anchorbrowser", "backend", "install"
        generate_completions_from_executable(bin/"anchorbrowser", "__completion")
      end
    end
  end

  test do
    system "#{bin}/anchorbrowser", "version"
  end
end
