# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Anchorbrowser < Formula
  desc "AnchorBrowser CLI for sessions, tasks, and identities"
  homepage "https://anchorbrowser.io"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/anchorbrowser/cli/releases/download/v0.1.7/anchorbrowser_0.1.7_darwin_amd64.tar.gz"
      sha256 "7fd3d58a41d8572bf58c00499523068313342cb4ec8c090ba1201f4dee50f9c4"

      define_method(:install) do
        bin.install "anchorbrowser"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/anchorbrowser/cli/releases/download/v0.1.7/anchorbrowser_0.1.7_darwin_arm64.tar.gz"
      sha256 "cf7a2cf95a845cecbd1f1cf1362d4a91b04f4746b74aa76d4ddcd6ab51b475af"

      define_method(:install) do
        bin.install "anchorbrowser"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/anchorbrowser/cli/releases/download/v0.1.7/anchorbrowser_0.1.7_linux_amd64.tar.gz"
      sha256 "9a5c38a7476d394735540689cd1cccd8315f21756bba74e8a338abc015ace5c6"
      define_method(:install) do
        bin.install "anchorbrowser"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/anchorbrowser/cli/releases/download/v0.1.7/anchorbrowser_0.1.7_linux_arm64.tar.gz"
      sha256 "aee07e7015b892fe7c8987a9b8332a700a2b38382e5bf0796028b93f9871fd2c"
      define_method(:install) do
        bin.install "anchorbrowser"
      end
    end
  end

  test do
    system "#{bin}/anchorbrowser", "version"
  end
end
