# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Anchorbrowser < Formula
  desc "AnchorBrowser CLI for sessions, tasks, and identities"
  homepage "https://anchorbrowser.io"
  version "0.1.14"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/anchorbrowser/cli/releases/download/v0.1.14/anchorbrowser_0.1.14_darwin_amd64.tar.gz"
      sha256 "4c82a9f2c7faa6fb14bde334fd0bd7de0664ad5efc6d8fe2fadfb3882bae5049"

      define_method(:install) do
        bin.install "anchorbrowser"
        generate_completions_from_executable(bin/"anchorbrowser", "__completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/anchorbrowser/cli/releases/download/v0.1.14/anchorbrowser_0.1.14_darwin_arm64.tar.gz"
      sha256 "519ed9d3a6dbccc70b768443768c0d6d92de31b8b7774bc4878a759eeffb86a5"

      define_method(:install) do
        bin.install "anchorbrowser"
        generate_completions_from_executable(bin/"anchorbrowser", "__completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/anchorbrowser/cli/releases/download/v0.1.14/anchorbrowser_0.1.14_linux_amd64.tar.gz"
      sha256 "e16ad8f677194dfa08e55f835c249cce65a78dfbe3b9210d45612e6546342adc"
      define_method(:install) do
        bin.install "anchorbrowser"
        generate_completions_from_executable(bin/"anchorbrowser", "__completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/anchorbrowser/cli/releases/download/v0.1.14/anchorbrowser_0.1.14_linux_arm64.tar.gz"
      sha256 "b00d438dc78194aa454ed6f502949ed03a28b871e8b8a27da980fe125ecc2641"
      define_method(:install) do
        bin.install "anchorbrowser"
        generate_completions_from_executable(bin/"anchorbrowser", "__completion")
      end
    end
  end

  test do
    system "#{bin}/anchorbrowser", "version"
  end
end
